"""empty message

Revision ID: 33f3082a4518
Revises: 95c8f179f1e9
Create Date: 2026-05-01 21:01:49.452559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33f3082a4518'
down_revision = '95c8f179f1e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('id_group', sa.Integer(), nullable=False),
    sa.Column('name_group', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_group'),
    sa.UniqueConstraint('name_group')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'group', ['group_id'], ['id_group'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('group_id')

    op.drop_table('group')
    # ### end Alembic commands ###
