"""empty message

Revision ID: 54f49768f138
Revises: f00bb8ea585c
Create Date: 2026-04-17 15:25:37.265228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54f49768f138'
down_revision = 'f00bb8ea585c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team',
    sa.Column('id_team', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('flag_url', sa.String(length=255), nullable=True),
    sa.Column('group_name', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id_team'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.add_column(sa.Column('home_team_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('away_team_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('stadium', sa.String(length=150), nullable=True))
        batch_op.create_foreign_key(None, 'team', ['away_team_id'], ['id_team'])
        batch_op.create_foreign_key(None, 'team', ['home_team_id'], ['id_team'])
        batch_op.drop_column('away_flag')
        batch_op.drop_column('home_flag')
        batch_op.drop_column('home_team')
        batch_op.drop_column('away_team')

    with op.batch_alter_table('prediction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prediction', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.add_column(sa.Column('away_team', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('home_team', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('home_flag', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('away_flag', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('stadium')
        batch_op.drop_column('away_team_id')
        batch_op.drop_column('home_team_id')

    op.drop_table('team')
    # ### end Alembic commands ###
