"""empty message

Revision ID: abe972ebe6dd
Revises: cd559fc2115e
Create Date: 2026-05-06 15:01:51.581603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abe972ebe6dd'
down_revision = 'cd559fc2115e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('match_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_audit_log_match_id'), ['match_id'], unique=False)
        batch_op.create_foreign_key(None, 'match', ['match_id'], ['id_match'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_audit_log_match_id'))
        batch_op.drop_column('match_id')

    # ### end Alembic commands ###
