"""empty message

Revision ID: ecc8dd0ec873
Revises: 6c0ae2565a03
Create Date: 2026-05-06 22:57:15.268079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecc8dd0ec873'
down_revision = '6c0ae2565a03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entry_fee', sa.Float(), nullable=True))

    op.execute('UPDATE "group" SET entry_fee = 0.0 WHERE entry_fee IS NULL')

    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.alter_column('entry_fee', nullable=False, server_default='0.0')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.drop_column('entry_fee')

    # ### end Alembic commands ###
